### ISSUE TITLE
Cannot download HTML report file

### ISSUE THREAD

**Issue by miniol** [omeka/plugin-Reports#19]
I'd like to refresh an issue that was already mentioned in #14 

<b>rsanc77</b> wrote:
<pre>The permission error is an environment problem where the file is created with   restricted permissions.</pre>

<b>patrickmj</b> wrote:
<pre>If I'm understanding this right, someone should be able to change the permissions on the server, and it isn't really a bug in Reports.</pre>

The problem is, that 'someone' should change the HTML report file every time it is generated.
The files in /files/reports directory are generated with different rights, depending on the file format:
- QR pdf (zip)' files  have set permissions 0644
- HTML report files  have set permissions 0600

The effect is that I can download the ZIP file containing PDF report but I can't download the HTML report file, since this is not readable.

Is it really an environment problem?

BTW, all the files added to objects have permissions set to 0644, so they can be opened in the browser.

**Comment by zerocrates** [comment]
Okay, it looks like we've finally figured out that this just comes from the use of `tempnam`, which sets restrictive permissions by default.
